language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - COMPOSER_VERSION=~1.0@dev

matrix:
    include:
        - php: 5.6
          env: COMPOSER_VERSION=dev-master#42bfe9c56adb555cc08e9ce2d32f6763ff75ae5d

    allow_failures:
        - php: hhvm

before_script:
    - composer self-update
    - composer install
    - composer require --dev --no-update phpunit/phpunit:@stable phpunit/php-code-coverage:@stable satooshi/php-coveralls:@dev composer/composer:${COMPOSER_VERSION}
    - composer update phpunit/php-code-coverage satooshi/php-coveralls composer/composer
    - mkdir -p ./build/logs

script:
    - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
    - 'echo ''src_dir: .'' >> ./.coveralls.yml'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ./vendor/bin/coveralls -v; fi;'

notifications:
    email: false
