language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

env:
    - COMPOSER_VERSION=''

matrix:
    include:
        - php: 5.6
          env: COMPOSER_VERSION='--version=1.0.0-alpha10'

    allow_failures:
        - php: hhvm

before_script:
    - mkdir -p ./build/logs
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=./build --filename=composer ${COMPOSER_VERSION}
    - ./build/composer install
    - ./build/composer require --dev --no-update phpunit/phpunit:@stable phpunit/php-code-coverage:@stable satooshi/php-coveralls:@dev
    - ./build/composer update phpunit/php-code-coverage satooshi/php-coveralls

script:
    - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_script:
    - 'echo ''src_dir: .'' >> ./.coveralls.yml'
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ./vendor/bin/coveralls -v; fi;'

notifications:
    email: false
